[build]
  command = "rm -f package-lock.json && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.12.0"
  NODE_OPTIONS = "--max_old_space_size=8192"

# Force dependencies to install in one step for caching
[build.processing]
  skip_processing = false

# Production context: all deploys from the Production branch
[context.production.environment]
  NODE_ENV = "production"